config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'callbacks'}
  root to: 'application#welcome'
  get 'gifts/most_expensive_gift', to: 'gifts#most_expensive_gift', as: 'meg'

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new', as: 'login'
    get 'signup', to: 'devise/registrations#new', as: 'signup'
  end 

 
  resources :people, only: [:index, :show] do 
    resources :gifts, only: [:index, :new, :edit, :show]
  end 

  resources :gifts 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord
    scope :most_expensive_gift, -> {where(cost: self.maximum(:cost))}
    validates :name, :cost, :notes, presence: true
    belongs_to :user
    belongs_to :person 

    accepts_nested_attributes_for :person, reject_if: :all_blank
end 

app/models/nice_list.rb
class NiceList < ActiveRecord::Base
    #has_many :gifts
   # has_many :gifts, through: :users
end 

app/models/person.rb
class Person < ApplicationRecord
    has_many :gifts
    has_many :users, through: :gifts
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  validates :username, :email, uniqueness: true 

  has_many :gifts
  has_many :people, through: :gifts

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.username = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0..20]
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome
      if user_signed_in?
        redirect_to people_path
      end 
    end 

    private

    def redirect
      if !user_signed_in?
        redirect_to '/'
      end 
    end 
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    
    def github
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user 
        flash[:notice] = "Congratulations, you're signed up!"
      else
        flash[:error] = "There was a problem"
        redirect_to new_user_registration_path
      end 
    end

    def failure
      flash[:error] = "There was a problem"
      redirect_to new_user_registration_path
    end 

end 

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
    before_action :redirect
    before_action :set_gift, only: [:show, :edit, :update, :destroy]

    def index
      #binding.pry
      if params[:person_id]
        @person = current_user.people.find_by(id: params[:person_id])
        @gifts = @person.gifts
      else
        @gifts = current_user.gifts
      end
    end 

    def most_expensive_gift
      @gifts = current_user.gifts.most_expensive_gift
  
      render :index
    end

    def new
      @gift = current_user.gifts.new(person_id: params[:person_id])
    end 

    def create
      @gift = current_user.gifts.build(gift_params)
      #binding.pry
      if @gift.save
        redirect_to gift_path(@gift)
      else
        render :new
      end 
    end 

    def show 
      @gift = current_user.gifts.find_by(id: params[:id])
    end 

    def edit
    end

    def update
      if @gift.update(gift_params)
        redirect_to gift_path(@gift) 
      else 
        render :edit 
      end      
    end 

    def destroy
      if @gift
        @gift.destroy
      end
      redirect_to gifts_path 
    end 

    private

    def set_gift
      @gift = current_user.gifts.find_by(id: params[:id])
      if !@gift
        flash[:error] = "I'm sorry, you don't have access to visit this page."
        redirect_to gifts_path
      end 
    end 
    
    def gift_params
      params.require(:gift).permit(:name, :cost, :notes, :person_id,
        person_attributes: [:name, :relationship])
    end 

end 

app/controllers/people_controller.rb
class PeopleController < ApplicationController

    before_action :redirect 

    def index
      @people = current_user.people.uniq
    end 

    def show
      @person = current_user.people.find_by(id: params[:id])
      if @person 
        @gifts = current_user.gifts.where(person_id: params[:id])
      else
        redirect_to people_path
      end 
    end 

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
 
    def sign_up_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nice_lists_helper.rb
module NiceListsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/application/welcome.html.erb
<div class='container'>
    <h2>Welcome to Santa's Workshop</h2>
    <h3>Login or signup to start your nice list!</h3>
</div>


app/views/gifts/_form.html.erb
<div class='container'>
  <%= form_for @gift do |f| %>

    <% if @gift.person_id.nil? %>
      <h3>Who is this gift for?</h3>
      <%= f.collection_select(:person_id, current_user.people.uniq, :id, :name, prompt: "Choose a person or create a new person below") %>
      <br><br>
    
      <%= f.fields_for :person, @gift.build_person do |p| %>
        <%= p.label 'Name' %>
        <%= p.text_field :name %>
      <% end %>

    <% else %>
      <%= f.hidden_field :person_id  %>
    <%end%>
    <br><br>

    <%= f.label 'Gift Name' %>
    <%= f.text_field :name %><br><br>
    <%= f.label 'Cost $' %>
    <%= f.text_field :cost %><br><br>
    <%= f.label 'Notes' %>
    <%= f.text_field :notes %><br><br>

    <%= f.submit "Add Gift" %>
  <% end %> 
  </div>

app/views/gifts/edit.html.erb
<div class='container'>
  <% if @gift.errors.any? %>
    <% @gift.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <br>
  <h2>Update Gift Information</h2>

  <%= render partial: "form", locals: {gift: @gift} %>
</div>

app/views/gifts/index.html.erb
<div class='background'>
  <div class="transbox">
    <% if params[:person_id] %>
      <h2><%= @person.name %>'s Gifts </h2>
      <%= link_to "Create New Gift", new_person_gift_path %><br><br>
    <% else %>
     <h2> All Gifts:</h2>
    <% end %>

    <% @gifts.each do |g| %>
      $<%= g.cost %>
      <%= link_to g.name, gift_path(g) %><br>
    <% end %>
  </div>
</div>




app/views/gifts/new.html.erb
<body>
<% if @gift.errors.any? %>
  <% @gift.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<br>

<%= render partial: "form", locales: {gift: @gift} %>
</body>

app/views/gifts/show.html.erb
<div class='background'>
  <div class="transbox">
    <h3> Present for: <%= @gift.person.name %><br></h3>
    <ul>
      <h4><%= @gift.name %><h4><br>
      Cost $<%= @gift.cost %><br>
      Notes: <%= @gift.notes %><br>
    </ul>
    <br>
    <%= link_to "Edit", edit_person_gift_path(@gift.person, @gift) %><br>
    <%= link_to "Delete Gift", @gift, method: :delete, data: { confirm: 'Are you sure?' }%><br>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav>
  <ul>
    <h1>Santas Workshop</h1>
    <hr>
    <%= link_to '<button type="button">Home</button>'.html_safe, root_path %>
    
    <% if !user_signed_in? %> 
      <%= link_to '<button type="button">Signup</button>'.html_safe, new_user_registration_path %>
      <%= link_to '<button type="button">Login</button>'.html_safe, new_user_session_path %>
    <% else %>
      <%= link_to '<button type="button">Logout</button>'.html_safe, destroy_user_session_path, method: "delete" %>
      <h2>Hello <%= current_user.username %> </h2>
      <br><br>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title >Santa's Workshop</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>
      html { 
        background: url("https://cdn.pixabay.com/photo/2017/10/26/19/45/christmas-2892235__480.png") no-repeat center center fixed; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
      }

      h1 {
        text-align: left;
        color: #e6ffff;
        font-size: 4em;
        font-family: Georgia, 'Times New Roman', Times, serif;
      }

      div.background {
        background: url(klematis.jpg) repeat;
      }

      div.transbox {
        margin: 30px;
        background-color: #ffffff;
        border: 1px solid black;
       opacity: 0.6;
      }

      div.transbox p {
       margin: 5%;
       font-weight: bold;
        color: #000000;
      }
  </style>


  <body>
    <%= render 'layouts/nav'%> 
    <%= yield %>
  </body>
</html>

app/views/nice_lists/new.html.erb
 <%= form_tag '/nice_lists' do %>
    <%= label_tag "Name" %>
    <%= text_field_tag :name%><br><br>
    <%= label_tag "Relationship" %>
    <%= text_field_tag :relationship%><br><br>
    <%= label_tag "Nice Rating" %>
    <%= text_field_tag :nice_rating%><br><br>

    <%= submit_tag "Submit" %>
  <% end %>

app/views/people/index.html.erb
<div class='background'>
  <div class="transbox">
    <h2> Begin by creating some new gifts for your loved ones!</h2>
    <h4><%= link_to "Create New Gift", new_gift_path %> -- <%= link_to "See All Gifts", gifts_path %> -- <%= link_to "See Most Expensive Gift", meg_path %></h4>
    <ul>
      <h3> My Nice List: </h3>
      <% @people.each do |p| %>
        <%= link_to p.name, person_gifts_path(p) %><br>
      <% end %>
    </ul>
  </div>
</div>

app/views/people/show.html.erb
<hr>
<h2><%= @person.name %></h2>




